- text: "- Ghế bệnh nhân"
- text: "- Đèn nha khoa cảm ứng"
- text: "-Ống nhổ bằng thủy tinh cao cấp"
- text: Hệ thống cung cấp nước sạch
- text: Ly nước súc miệng
- text: "-Mâm chính"
- text: "Đèn xem phim X-ray"
- text: "Bàn phím điều khiển"
- text: Tay xịt 3 chức năng
- text: Hai vị trí tay khoan siêu tốc
- text: Một vị trí cho tay khoan chậm
- text: "-hệ thống trợ thủ:"
- text: Hút phẫu thuật
- text: Hút nước bọt
- text: Tay xịt hơi nước 3 chức năng
- text: Bàn phím điều khiển
- text: Pedan điều khiển
- text: "-Ghế nha sĩ"
